version: "3.9"

services:

  postgres:
    image: postgres:latest
    container_name: pg_ww
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - ww_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cache:
    image: redis:latest
    container_name: cache_ww
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ww_data:/data
    ports:
      - "6379:6379"

  web:
    env_file:
      - .env
    build: ./src
    container_name: django_ww
    environment:
      POSTGRES_HOST: "postgres"
      CELERY_BROKER_URL: "redis://cache:6379/0"
      CASHES: "redis://cache:6379/0"
    command: sh -c "
          python manage.py runserver 0.0.0.0:8000 && 
          python manage.py migrate"

    volumes:
      - ./src:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - cache

  celery:
    env_file:
      - .env
    build: ./src
    container_name: celery_ww
    environment:
      POSTGRES_HOST: "postgres"
      CELERY_BROKER_URL: "redis://cache:6379/0"
      CASHES: "redis://cache:6379/0"
    command: watchfiles --filter python 'celery -A config worker -E --beat --scheduler django --loglevel=info'
    volumes:
      - ./src:/usr/src/app/
    depends_on:
      - web
      - postgres
      - cache

  flower:
    env_file:
      - .env
    build: ./src
    container_name: flower_ww
    environment:
      POSTGRES_HOST: "postgres"
      CELERY_BROKER_URL: "redis://cache:6379/0"
      CASHES: "redis://cache:6379/0"
      FLOWER_UNAUTHENTICATED_API: True
    command: celery -A config flower --port=5555 --broker=redis://cache:6379/0
    volumes:
      - ./src:/usr/src/app/
    ports:
      - "5555:5555"
    depends_on:
      - web
      - postgres
      - cache
      - celery

volumes:
  ww_data:
